from __future__ import annotations
import json
import os
from typing import Dict, Tuple

from .models import Project, Category, ImageAnnotation, PALETTE
from .mask_manager import MaskManager


def save_coco(
    project: Project,
    mask_managers: Dict[int, MaskManager],  # image_id → MaskManager
    output_path: str,
    image_dir: str = "",
) -> None:
    """
    Save project to COCO JSON.
    Masks are converted to polygon contours here (only at save time).
    """
    data: dict = {
        "info": {"description": "Generated by Polygon Labeler"},
        "licenses": [],
        "categories": [
            {"id": c.id, "name": c.name, "supercategory": c.supercategory}
            for c in project.categories
        ],
        "images": [],
        "annotations": [],
    }

    global_ann_id = 1
    for img in project.images:
        if image_dir:
            try:
                fname = os.path.relpath(img.file_path, image_dir).replace("\\", "/")
            except ValueError:
                fname = os.path.basename(img.file_path)
        else:
            fname = os.path.basename(img.file_path)

        data["images"].append({
            "id": img.image_id,
            "file_name": fname,
            "width": img.width,
            "height": img.height,
        })

        mgr = mask_managers.get(img.image_id)
        if mgr:
            anns = mgr.to_coco_annotations(img.image_id)
            for ann in anns:
                ann["id"] = global_ann_id
                global_ann_id += 1
            data["annotations"].extend(anns)

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def load_coco(
    json_path: str,
    image_dir: str = "",
) -> Tuple[Project, Dict[int, MaskManager]]:
    """
    Load COCO JSON.
    Returns (project, mask_managers) where mask_managers maps image_id → MaskManager
    with COCO polygons rasterized into numpy masks.
    """
    with open(json_path, encoding="utf-8") as f:
        data = json.load(f)

    project = Project()

    for cat_data in data.get("categories", []):
        idx = (cat_data["id"] - 1) % len(PALETTE)
        cat = Category(
            id=cat_data["id"],
            name=cat_data["name"],
            color=PALETTE[idx],
            supercategory=cat_data.get("supercategory", ""),
        )
        project.categories.append(cat)
        project._next_cat_id = max(project._next_cat_id, cat.id + 1)

    img_map: dict = {}
    for img_data in data.get("images", []):
        fname = img_data["file_name"]
        path = os.path.join(image_dir, fname) if (image_dir and not os.path.isabs(fname)) else fname
        img = ImageAnnotation(
            image_id=img_data["id"],
            file_path=path,
            width=img_data["width"],
            height=img_data["height"],
        )
        project.images.append(img)
        img_map[img.image_id] = img
        project._next_img_id = max(project._next_img_id, img.image_id + 1)

    # Group annotations by image_id
    anns_by_image: dict = {}
    for ann in data.get("annotations", []):
        anns_by_image.setdefault(ann["image_id"], []).append(ann)

    # Rasterize COCO polygons → MaskManager per image
    mask_managers: Dict[int, MaskManager] = {}
    for img_id, anns in anns_by_image.items():
        img = img_map.get(img_id)
        if img is None:
            continue
        mgr = MaskManager(img.width, img.height)
        mgr.load_from_coco(anns)
        mask_managers[img_id] = mgr

    return project, mask_managers
